<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\SharedCore\SharedCore.Persistence\SharedCore.Persistence.csproj" />
        <ProjectReference Include="..\Todo.Domain\Todo.Domain.csproj" />
        <ProjectReference Include="..\Todo.Common\Todo.Common.csproj" />
    </ItemGroup>

</Project>