<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8"/>
        <PackageReference Include="Testcontainers.MsSql" Version="4.12.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\SharedCore\SharedCore.Persistence\SharedCore.Persistence.csproj"/>
    </ItemGroup>

</Project>
