using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace SharedCore.Presentation.OpenApi;

/// <summary>
/// The <see cref="ProblemDetails"/> schema transformer.
/// </summary>
/// <seealso cref="IOpenApiOperationTransformer"/>
[ExcludeFromCodeCoverage]
public class ProblemDetailsSchemaTransformer : IOpenApiSchemaTransformer
{
    /// <inheritdoc />
    public Task TransformAsync(OpenApiSchema schema, OpenApiSchemaTransformerContext context,
        CancellationToken cancellationToken)
    {
        // Intercept the ProblemDetails schema generation
        if (context.JsonTypeInfo.Type != typeof(ProblemDetails))
        {
            return Task.CompletedTask;
        }

        schema.Description = "A standardized format for returning error information in HTTP responses (RFC 9457).";

        if (schema.Properties is null)
        {
            return Task.CompletedTask;
        }

        // Notice the safe cast to 'OpenApiSchema' here to unlock the setters
        if (schema.Properties.TryGetValue("type", out var typeSchema) && typeSchema is OpenApiSchema concreteTypeSchema)
        {
            concreteTypeSchema.Description = "A URI reference that identifies the problem type.";
            concreteTypeSchema.Example = JsonValue.Create("https://tools.ietf.org/html/rfc9110#section-15.5.1");
        }

        if (schema.Properties.TryGetValue("title", out var titleSchema) &&
            titleSchema is OpenApiSchema concreteTitleSchema)
        {
            concreteTitleSchema.Description = "A short, human-readable summary of the problem type.";
            concreteTitleSchema.Example = JsonValue.Create("Bad Request");
        }

        if (schema.Properties.TryGetValue("status", out var statusSchema) &&
            statusSchema is OpenApiSchema concreteStatusSchema)
        {
            concreteStatusSchema.Description =
                "The HTTP status code generated by the origin server for this occurrence of the problem.";
            concreteStatusSchema.Example = JsonValue.Create(400);
        }

        if (schema.Properties.TryGetValue("detail", out var detailSchema) &&
            detailSchema is OpenApiSchema concreteDetailSchema)
        {
            concreteDetailSchema.Description =
                "A human-readable explanation specific to this occurrence of the problem.";
            concreteDetailSchema.Example = JsonValue.Create("A validation error has occurred.");
        }

        if (schema.Properties.TryGetValue("instance", out var instanceSchema) &&
            instanceSchema is OpenApiSchema concreteInstanceSchema)
        {
            concreteInstanceSchema.Description =
                "A URI reference that identifies the specific occurrence of the problem.";
            concreteInstanceSchema.Example = JsonValue.Create("POST /api/Users");
        }

        return Task.CompletedTask;
    }
}