<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>ModuleTemplate-480adbee-9136-4f7b-9ee5-32d5021b7a6f</UserSecretsId>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <!--#if (IsToAddDocker) -->
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <!--#endif -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.11.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Aspire\Aspire.ServiceDefaults\Aspire.ServiceDefaults.csproj"/>
        <ProjectReference Include="..\..\SharedCore\SharedCore.Presentation\SharedCore.Presentation.csproj"/>
        <ProjectReference Include="..\ModuleTemplate.Application\ModuleTemplate.Application.csproj"/>
    </ItemGroup>

    <!-- This is needed to add documentation about ProblemDetails to the OpenAPI document -->
    <Target Name="AddOpenApiDependencies" AfterTargets="ResolveReferences">
        <ItemGroup>
            <AdditionalFiles
                    Include="@(ReferencePath->'%(RootDir)%(Directory)%(Filename).xml')"
                    Condition="'%(ReferencePath.Filename)' == 'Microsoft.AspNetCore.Http.Abstractions'"
                    KeepMetadata="Identity;HintPath"/>
        </ItemGroup>
    </Target>

    <ItemGroup>
        <Folder Include="Dtos\V1\"/>
        <Folder Include="Endpoints\V1\"/>
        <Folder Include="MappingExtensions\V1\"/>
    </ItemGroup>

</Project>
