<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" Version="8.1.0"/>
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4"/>
        <PackageReference Include="OpenIddict.AspNetCore" Version="6.2.0"/>
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0"/>
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0"/>
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0"/>
        <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.1.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SharedCore.Application\SharedCore.Application.csproj"/>
    </ItemGroup>

</Project>
