<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.8"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SharedCore.Domain\SharedCore.Domain.csproj"/>
        <ProjectReference Include="..\SharedCore.Common\SharedCore.Common.csproj"/>
    </ItemGroup>

</Project>
