<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\SharedCore\SharedCore.Domain\SharedCore.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.5"/>
    </ItemGroup>

</Project>
