<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>identity-46f52c23-2adf-42d9-b4ff-933494d8195f</UserSecretsId>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <!--#if (IsToAddDocker) -->
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <!--#endif -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.10.3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Aspire\Aspire.ServiceDefaults\Aspire.ServiceDefaults.csproj"/>
        <ProjectReference Include="..\..\SharedCore\SharedCore.Presentation\SharedCore.Presentation.csproj"/>
        <ProjectReference Include="..\Identity.Application\Identity.Application.csproj"/>
    </ItemGroup>

</Project>
