<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="OpenIddict.AspNetCore" Version="6.2.0"/>
        <PackageReference Include="OpenIddict.Quartz" Version="6.2.0"/>
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.14.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\SharedCore\SharedCore.Application\SharedCore.Application.csproj"/>
        <ProjectReference Include="..\Identity.Persistence\Identity.Persistence.csproj"/>
    </ItemGroup>

</Project>
