<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\SharedCore\SharedCore.Presentation\SharedCore.Presentation.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="9.0.4"/>
    </ItemGroup>

</Project>
