@startfiles

/src/Aspire/Aspire.AppHost/
/src/Aspire/Aspire.ServiceDefaults/
/src/ModuleA/ModuleA.Presentation/
/src/ModuleA/ModuleA.Application/
/src/ModuleA/ModuleA.Persistence/
/src/ModuleA/ModuleA.Domain/
/src/ModuleA/ModuleA.Common/
/src/SharedCore/SharedCore.Presentation/
/src/SharedCore/SharedCore.Application/
/src/SharedCore/SharedCore.Persistence/
/src/SharedCore/SharedCore.Domain/
/src/SharedCore/SharedCore.Common/
/src/Directory.Build.props
/tests/ModuleA/ModuleA.Presentation.IntegrationTests/
/tests/ModuleA/ModuleA.Application.Tests/
/tests/ModuleA/ModuleA.Persistence.IntegrationTests/
/tests/ModuleA/ModuleA.Domain.Tests/
/tests/ModuleA/ModuleA.Common.Tests/
/tests/SharedCore/SharedCore.Presentation.Tests/
/tests/SharedCore/SharedCore.Application.Tests/
/tests/SharedCore/SharedCore.Persistence.IntegrationTests/
/tests/SharedCore/SharedCore.Common.Tests/
/tests/Directory.Build.props
/tests/CodeCoverage-settings.xml
/.editorconfig
/.gitignore
/Directory.Build.props
/global.json
/LICENSE
/README.md
/SolutionName.slnx

@endfiles