<Project>

    <!-- import parent: https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory#use-case-multi-level-merging -->
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <ItemGroup>
        <InternalsVisibleTo Include="$(AssemblyName).Tests" />
        <InternalsVisibleTo Include="$(AssemblyName).IntegrationTests" />
        <InternalsVisibleTo Include="Architecture.Tests" />
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>

</Project>